FROM node:18-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG GCS_BUCKET_NAME
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV GCS_BUCKET_NAME=$GCS_BUCKET_NAME
COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
